### ISSUE TITLE
Question : what are the differences related to the original ?

### ISSUE THREAD

**Issue by StefH** [jetreports/EPPlus#26]

**Comment by emdelaney** [comment]
Hi Stef! There are three main differences between this fork and the EPPlus mainline: a large number of bugfixes and improvements; a coding standard; and much more frequent development and updates.

**We enforce [a Coding Standard](https://github.com/jetreports/EPPlus/wiki/Coding-Standard), which requires, among other things:**
- Unit tests for all code changes,
- Full-word variable names,
- XML method comments,
- The removal of commented-out code,
- And more!

**This fork also contains dozens of bug fixes and enhancements:**

- Improved excel function implementations,
- Better support for Excel-generated Charts,
- Bugfixes to the CellStore, ExcelWorkbook/Worksheet, and other core classes,
- Other fixes and improvements as noted in the commit history.

Because our products use EPPlus every day, we're regularly making updates and improvements; the full details are in the [commit history](https://github.com/jetreports/EPPlus/commits/FixEOMONTHFunction) . This month we are adding unit tests and improving support for most of the DateTime excel functions, for example. 

We add support for features as we need them, and are happy to take bug reports (with unit tests; we'll let you know if we plan to fix it, or point you in the right direction to fix it yourself). We're also happy to include pull requests that have comprehensive unit test coverage and adhere to our coding standard.

**Comment by StefH** [comment]
Do you also provide the NuGet ? (https://www.nuget.org/packages/EPPlus/) ?

**Comment by emdelaney** [comment]
Nope.
